### PR TITLE
Play 2.7 support

### PR DESCRIPTION
**Pull request by salomatov**
This is replication of [PR](https://github.com/jaliss/securesocial/pull/621) from original securesocial repo which seems to be abandoned.

- org.apache.commons.lang3.reflect.TypeUtils is no longer a dependency
- most changes related to play.libs.concurrent.HttpExecution.defaultContext no longer available

### CODE REVIEW

**Comment by k4200** [comment]
@salomatov 
Thank you for the PR. Can you write a bit about the PR in the description?

**Comment by salomatov** [comment]
@k4200 my bad, sorry.

**Comment by k4200** [comment]
@salomatov 
It's been a long time. Sorry for the delay.

There are some deprecation warnings. Can you fix them? Play 2.8 is already out, and some of them might have been removed, or will be removed soon.

**Comment by k4200** [comment]
Thank you for the contribution.

**Pull request merged**
